### ISSUE TITLE
[Feature] Add a check to see if a user is walk-in

### ISSUE THREAD

**Issue by abdullah50053** [acmutd/hackutd-ix-site#39]
# Overview

Currently, there is no way to support walk-ins in HackPortal.

# Proposal

Add a check on the organizer side to see if a user has registered after a certain cutoff time. 
This cutoff time will be determined by a super-admin on the Admin portal. This date should be changeable, with any registrations prior to the cutoff being updated to their appropriate status. 
During check-in, a popup will display on the admin's device informing them that the hacker is a walk-in or registered after the deadline. Admins will then have the ability to confirm or deny check-in. A hacker can be checked in later if their entry was denied.  This functionality is limited to check-in, and a hacker's status as late registration should not carry over to other scans.

**Comment by NickBurnett** [comment]
ok

**Comment by NickBurnett** [comment]
@abdullah50053 Do we want there to be a separate settings manager in the firestore instance? I ask because we can just put this in the hackportal config, but you mention that
> The cutoff time will be determined by a super-admin on the Admin portal

Rather than some configuration, you're suggesting something they can change within the app itself. I'm personally in favor of keeping it in the hackportal config but let me know what you're going for with that and I'll implement it.

**Comment by MichaelZhao21** [comment]
@NickBurnett Abdullah says that it's fine for the hackutd 9 site to put it in the config, but ideally we would have it on the admin console. 

The reason for having admins be able to dynamically change it is on the day of, when we decide to accept walk-ins, we can just set the cutoff date to some time in the future, and it would just allow anyone to be checked in without showing the popup.
